### ISSUE TITLE
进度问题

### ISSUE THREAD

**Issue by czboosj** [LeoiOS/LCDownloadManager#2]
我发现我在下载的时候,有时候中途暂停,在开始后,进度会错误,一直下载到100+暂停前进度% 如120% , 搞不懂为什么, 而且看代码,是AF传入的错误,因为当时检测已下载还是0 的,有人遇到过吗, 是af bug  还是 , 服务器, 还是怎么

**Comment by iTofu** [comment]
请描述详细过程？

**Comment by czboosj** [comment]
operation2 = nil
        operation2 = LCDownloadManager.downloadFileWithURLString(url, cachePath: downName, progress: { (press, totalBytes, totalBytesExpected) -> Void in
             // Getdevice.println("下载进度 :(press) :(totalBytes)  :(totalBytesExpected)")
            // 这里, 下载的url 是一个视频url , 有时存在,不是一定出现, 这里返回  press 大于1  ,totalBytes>totalBytesExpected

```
        }

        }, success: { (operation, obj,filePath) -> Void in


        }, failure: { (operation, error) -> Void in

    })
```

**Comment by iTofu** [comment]
我靠，totalBytes怎么会大于totalBytesExpected，url中的文件发生了变化吗？

**Comment by czboosj** [comment]
不太清楚,所以很奇怪, 感觉是又从0 开始下载, 但是返回数据进度错误, 下载的文件应该也没追加,因为完成后能正常播放, 开启我觉得是服务器问题,后来我用你demo 里面的地址也会出现,  关键是在你demo 中暂停没发现这个情况 , 我这里也不是一定会出现 ,  对了, 出现的话, 是中途暂停, 在开始, 不退出应用 ,

**Comment by iTofu** [comment]
....好吧这个库确实需要抽空重写了，慎用
